-- 기존 시퀀스 삭제
DROP SEQUENCE WM_MEMBER_HOME_SEQ;
DROP SEQUENCE WM_MEMBER_SEQ;
DROP SEQUENCE WM_COUPON_SEQ;
DROP SEQUENCE WM_PRODUCT_SEQ;
DROP SEQUENCE WM_ZZIM_SEQ;
DROP SEQUENCE WM_BOARD_ANSWER_SEQ;
DROP SEQUENCE WM_BOARD_ASK_SEQ;
DROP SEQUENCE WM_BOARD_FAQ_SEQ;
DROP SEQUENCE WM_BOARD_ANNOUNCE_SEQ;
DROP SEQUENCE WM_ORDER_DETAIL_SEQ;
DROP SEQUENCE WM_ORDER_SEQ;
DROP SEQUENCE WM_CART_SEQ;

-- 새로운 시퀀스 생성
CREATE SEQUENCE WM_MEMBER_HOME_SEQ NOCACHE;
CREATE SEQUENCE WM_MEMBER_SEQ NOCACHE;
CREATE SEQUENCE WM_COUPON_SEQ NOCACHE;
CREATE SEQUENCE WM_PRODUCT_SEQ NOCACHE;
CREATE SEQUENCE WM_ZZIM_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ANNOUNCE_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_FAQ_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ASK_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ANSWER_SEQ NOCACHE;
CREATE SEQUENCE WM_CART_SEQ NOCACHE;
CREATE SEQUENCE WM_ORDER_SEQ NOCACHE;
CREATE SEQUENCE WM_ORDER_DETAIL_SEQ NOCACHE;

-- 기존 테이블 삭제
DROP TABLE WM_ORDER_DETAIL;
DROP TABLE WM_ORDER;
DROP TABLE WM_CART;
DROP TABLE WM_BOARD_ANSWER;
DROP TABLE WM_BOARD_ASK;
DROP TABLE WM_BOARD_FAQ;
DROP TABLE WM_BOARD_ANNOUNCE;
DROP TABLE WM_ZZIM;
DROP TABLE WM_COUPON;
DROP TABLE WM_PRODUCT_MANAGE;
DROP TABLE WM_PRODUCT;
DROP TABLE WM_MEMBER_EXP;
DROP TABLE WM_MEMBER_HOME;
DROP TABLE WM_MEMBER;




-- 회원 정보 저장을 위한 테이블
CREATE TABLE WM_MEMBER (
    MEM_NUM          NUMBER             NOT NULL,  -- 회원 번호
    MEM_NAME         VARCHAR2(30 BYTE)  NOT NULL,  -- 회원 이름
    MEM_PASSWD       VARCHAR2(20 BYTE)  NOT NULL,  -- 회원 비밀번호
    MEM_CELL         VARCHAR2(15 BYTE)  NOT NULL UNIQUE,  -- 회원 휴대폰
    MEM_EMAIL        VARCHAR2(50 BYTE)  NOT NULL UNIQUE,  -- 회원 이메일
    MEM_ZIPCODE      NUMBER(5)          NOT NULL,  -- 회원 우편번호
    MEM_ADDRESS1     VARCHAR2(50 BYTE)  NOT NULL,  -- 회원 주소1
    MEM_ADDRESS2     VARCHAR2(50 BYTE)  NOT NULL,  -- 회원 주소2
    MEM_BIRTH        VARCHAR2(10 BYTE)   NOT NULL,  -- 회원 생년월일
    MEM_GENDER       NUMBER(1)          NOT NULL,  -- 회원 성별
    MEM_MDATE        DATE,                   -- 회원 수정일
    MEM_AUTH          NUMBER(1)                NOT NULL,  -- 회원 권한
    MEM_REG_DATE      DATE                     NOT NULL,  -- 회원 가입일
    MEM_STOP_DATE     DATE,                   -- 회원 휴먼일
    MEM_EXP_DATE      DATE,                   -- 회원 만료일

CONSTRAINT PK_WM_MEMBER PRIMARY KEY(MEM_NUM)
);


-- 배송지 저장을 위한 테이블
CREATE TABLE WM_MEMBER_HOME (
    MEM_NUM            NUMBER            NOT NULL,  -- 회원 번호
    MEM_HOME_NUM       NUMBER            NOT NULL,  -- 집 주소 번호
    MEM_HOME_CELL      VARCHAR2(15 BYTE) NOT NULL,  -- 집 전화번호
    MEM_HOME_ZIPCODE   NUMBER(5)         NOT NULL,  -- 집 우편번호
    MEM_HOME_ADDRESS1  VARCHAR2(90 BYTE) NOT NULL,  -- 집 주소1(자동)
    MEM_HOME_ADDRESS2  VARCHAR2(90 BYTE) NOT NULL,  -- 집 주소2(수기)
    
    CONSTRAINT PK_WM_MEMBER_HOME PRIMARY KEY(MEM_HOME_NUM),
    CONSTRAINT FK_WM_MEMBER_HOME FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER (MEM_NUM) ON DELETE CASCADE
);

-- 탈퇴한 회원 정보를 저장하기 위한 테이블
CREATE TABLE  WM_MEMBER_EXP (
    MEM_EMAIL          VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 탈퇴한 회원 이메일
    MEM_REG_DATE       DATE,                               -- 가입일
    MEM_EXP_DATE       DATE                                -- 탈퇴일
);


-- 제품 상세
CREATE TABLE WM_PRODUCT(
        PRODUCT_NUM        NUMBER(5)        NOT NULL,        -- 제품 식별 번호
        PRODUCT_NAME       VARCHAR2(60)     NOT NULL,        -- 제품 이름
        PRODUCT_TITLE      VARCHAR2(100)    NOT NULL,        -- 제품 타이틀
        PRODUCT_INFO       VARCHAR2(1000)   NOT NULL,        -- 제품 정보
        PRODUCT_PHOTO1     VARCHAR2(100)    NOT NULL,        -- 제품 사진1
        PRODUCT_PHOTO2     VARCHAR2(100)    NOT NULL,        -- 제품 사진 2
        PRODUCT_REAL_PRICE NUMBER(7)        NOT NULL,        -- 제품 원가
        PRODUCT_PRICE      NUMBER(7)        NOT NULL,        -- 제품 판매가
        PRODUCT_STOCK      NUMBER(7)        NOT NULL,        -- 제품 재고
 CONSTRAINT PK_WM_PRODUCT PRIMARY KEY (PRODUCT_NUM)

);

-- 제품 관리
CREATE TABLE WM_PRODUCT_MANAGE (
  PRODUCT_NUM      NUMBER     NOT NULL, 
  PRODUCT_CATEGORY NUMBER(2)  NOT NULL UNIQUE, 
  PRODUCT_STATUS   NUMBER     NOT NULL,          -- 제품 상태 : 1: 판매중 2: 판매불가(품절 등) 
  CONSTRAINT PK_WM_PRODUCT_MANAGE PRIMARY KEY (PRODUCT_NUM) , 
  CONSTRAINT FK_WM_PRODUCT_MANAGE FOREIGN KEY (PRODUCT_NUM) REFERENCES WM_PRODUCT(PRODUCT_NUM) ON DELETE CASCADE
);

--쿠폰
CREATE TABLE WM_COUPON (
  COUPON_NUM       NUMBER  NOT NULL,                 -- 쿠폰 번호
  COUPON_NAME      VARCHAR2(50) UNIQUE NOT NULL,     -- 쿠폰 이름
  COUPON_INFO      VARCHAR2(100)       NOT NULL,     -- 쿠폰 정보
  COUPON_PRICE     NUMBER(7)           NOT NULL,     -- 쿠폰 가격
  COUPON_STATUS    NUMBER(1) DEFAULT 1 NOT NULL,     --1:미사용 2:사용 3:기간만료 
  MEM_NUM          NUMBER(5),
  PRODUCT_CATEGORY NUMBER(2) NOT NULL,
  CONSTRAINT PK_WM_COUPON PRIMARY KEY (COUPON_NUM), -- 이 부분이 추가되어야 합니다
  CONSTRAINT FK_WM_COUPON FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER(MEM_NUM) ON DELETE CASCADE,
  CONSTRAINT FK2_WM_COUPON FOREIGN KEY (PRODUCT_CATEGORY) REFERENCES WM_PRODUCT_MANAGE(PRODUCT_CATEGORY) ON DELETE CASCADE
);


-- 찜 목록을 저장하기 위한 테이블
CREATE TABLE WM_ZZIM (
	ZZIM_NUM    NUMBER(5) NOT NULL,          -- 찜 번호
	MEM_NUM     NUMBER(5) NOT NULL,          -- 회원 번호
	PRODUCT_NUM NUMBER(5) NOT NULL,          -- 제품 번호
	CONSTRAINT PK_ZZIM PRIMARY KEY(ZZIM_NUM),
	CONSTRAINT FK_MEMBER_ZZIM FOREIGN KEY(MEM_NUM) REFERENCES WM_MEMBER(MEM_NUM) ON DELETE CASCADE,
	CONSTRAINT FK2_PRODUCT_ZZIM FOREIGN KEY(PRODUCT_NUM) REFERENCES WM_PRODUCT(PRODUCT_NUM) ON DELETE CASCADE
);


-- 공지사항 정보를 저장하기 위한 테이블
CREATE TABLE WM_BOARD_ANNOUNCE (
	ANN_NUM NUMBER,                            -- 공지사항 번호
	ANN_TITLE VARCHAR2(300) NOT NULL,          -- 공지사항 제목
	ANN_CONTENT VARCHAR2(1000) NOT NULL,       -- 공지사항 내용
	ANN_DATE DATE DEFAULT SYSDATE NOT NULL,    -- 등록일
	CONSTRAINT PK_WM_BOARD_ANNOUNCE PRIMARY KEY (ANN_NUM)
);


-- FAQ 정보를 저장하기 위한 테이블
CREATE TABLE WM_BOARD_FAQ (
	FAQ_NUM NUMBER,                         -- FAQ 번호
	FAQ_TITLE VARCHAR2(300) NOT NULL,       -- FAQ 제목
	FAQ_CONTENT VARCHAR2(3000) NOT NULL,    -- FAQ 내용
	FAQ_CATEGORY NUMBER(1) DEFAULT 1 NOT NULL, -- FAQ 카테고리
	FAQ_DATE DATE DEFAULT SYSDATE NOT NULL, -- FAQ 작성일
	CONSTRAINT PK_WM_BOARD_FAQ PRIMARY KEY (FAQ_NUM)
);



-- 1:1 문의 게시판 정보를 저장하기 위한 테이블
CREATE TABLE WM_BOARD_ASK (
	ASK_NUM NUMBER,                          -- 문의글 번호
	MEM_NUM NUMBER NOT NULL,                 -- 문의자 번호
	ASK_TITLE VARCHAR2(100) NOT NULL,        -- 문의글 제목
	ASK_CONTENT VARCHAR2(1000) NOT NULL,     -- 문의글 내용
	ASK_PHOTO1 VARCHAR2(100),                -- 문의글 사진 첨부
	ASK_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 문의글 작성 날짜
	CONSTRAINT PK_WM_BOARD_ASK PRIMARY KEY (ASK_NUM),
	CONSTRAINT FK_WM_BOARD_ASK FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER (MEM_NUM) ON DELETE CASCADE
);


-- 1:1 문의 게시판 답변 정보를 저장하기 위한 테이블
CREATE TABLE WM_BOARD_ANSWER (
	ASK_NUM NUMBER NOT NULL,                   -- 문의글 번호
    MEM_NUM NUMBER NOT NULL,                   -- 문의자 번호
	ANSWER_NUM NUMBER(5),                      -- 답변 번호
	ANSWER_CONTENT VARCHAR2(1000) NOT NULL,    -- 답변 내용
	ANSWER_PHOTO VARCHAR2(100),                -- 답변 사진 첨부
	ANSWER_DATE DATE DEFAULT SYSDATE NOT NULL, -- 답변 작성 날짜
	CONSTRAINT PK_WM_BOARD_ANSWER PRIMARY KEY (ANSWER_NUM),
	CONSTRAINT FK1_WM_BOARD_ANSWER FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER (MEM_NUM) ON DELETE CASCADE,
    CONSTRAINT FK2_WM_BOARD_ANSWER FOREIGN KEY (ASK_NUM) REFERENCES WM_BOARD_ASK (ASK_NUM) ON DELETE CASCADE
);


-- 장바구니 정보를 저장하기 위한 테이블
CREATE TABLE WM_CART (
	CART_NUM     NUMBER(20)   NOT NULL, -- 장바구니 번호
	PRODUCT_NUM  NUMBER       NOT NULL, -- 제품 번호
	MEM_NUM      NUMBER       NOT NULL, -- 회원 번호
	PRODUCT_QTY  NUMBER       NOT NULL, -- 제품 수량
	CONSTRAINT PK_CART PRIMARY KEY (CART_NUM),
	CONSTRAINT FK1_CART FOREIGN KEY (PRODUCT_NUM) REFERENCES WM_PRODUCT (PRODUCT_NUM) ON DELETE CASCADE,
	CONSTRAINT FK2_CART FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER (MEM_NUM) ON DELETE CASCADE
);

-- 주문 정보를 저장하기 위한 테이블
CREATE TABLE WM_ORDER (
	ORDER_NUM             NUMBER     NOT NULL,    -- 주문번호
	MEM_NUM               NUMBER     NOT NULL,    -- 회원번호
	MEM_HOME_NUM          NUMBER     NOT NULL,    -- 주소(배송지 테이블과 연결)
	ORDER_TOTAL_PRICE     NUMBER(10) NOT NULL,    -- 구매금액(상품개수*상품가격)
	ORDER_STATUS          NUMBER(1)  NOT NULL,    -- 상품 주문 상태 (0: 주문 완료, 1: 배송중, 2: 배송완료)
	ORDER_DATE            DATE       NOT NULL,    -- 구매일
	ORDER_NOTICE          VARCHAR2(100),          -- 배송요청사항
	RECEIVER_NAME         VARCHAR2(20) NOT NULL,  -- 수령자 이름
	RECEIVER_PHONE        VARCHAR2(20) NOT NULL,  -- 수령자 휴대폰번호
	ORDERER_NAME          VARCHAR2(20) NOT NULL,  -- 주문자 이름
	ORDERER_PHONE         VARCHAR2(20) NOT NULL,  -- 주문자 휴대폰번호
	DELIVERY_METHOD       VARCHAR2(40) NOT NULL,  -- 배송방법
	PAY_METHOD            VARCHAR2(200) NOT NULL, -- 결제방법
	CARD_NAME             VARCHAR2(50),           -- 카드 이름
	CARD_PAY              VARCHAR2(20),           -- 할부개월
	CONSTRAINT PK_ORDER PRIMARY KEY (ORDER_NUM),
	CONSTRAINT FK1_ORDER FOREIGN KEY (MEM_NUM) REFERENCES WM_MEMBER (MEM_NUM) ON DELETE SET NULL,
	CONSTRAINT FK2_ORDER FOREIGN KEY (MEM_HOME_NUM) REFERENCES WM_MEMBER_HOME (MEM_HOME_NUM) ON DELETE SET NULL
);

-- 주문 상세 정보를 저장하기 위한 테이블
CREATE TABLE WM_ORDER_DETAIL (
	ORDER_DETAIL_NUM     NUMBER     NOT NULL,   -- 구매상세 식별번호
	ORDER_NUM            NUMBER     NOT NULL,   -- 주문번호
	PRODUCT_NUM          NUMBER(5)  NOT NULL,   -- 제품번호
	ORDER_PRODUCT_NAME   VARCHAR2(60) NOT NULL, -- 제품명
	ORDER_PRODUCT_PRICE  NUMBER(7)  NOT NULL,   -- 제품구매가
	ORDER_PRODUCT_QTY    NUMBER(5)  NOT NULL,   -- 제품구매개수
	ORDER_PRODUCT_TOTAL  NUMBER(7)  NOT NULL,   -- 제품구매총액
	CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (ORDER_DETAIL_NUM),
	CONSTRAINT FK1_ORDER_DETAIL FOREIGN KEY (ORDER_NUM) REFERENCES WM_ORDER (ORDER_NUM) ON DELETE CASCADE,
	CONSTRAINT FK2_ORDER_DETAIL FOREIGN KEY (PRODUCT_NUM) REFERENCES WM_PRODUCT (PRODUCT_NUM) ON DELETE SET NULL
);
