DROP SEQUENCE CP_SEQ;
DROP SEQUENCE ORDER_DETAIL_SEQ;
DROP SEQUENCE ORDER_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE BOARD_ANSWER_SEQ;
DROP SEQUENCE BOARD_ASK_SEQ;
DROP SEQUENCE BOARD_FAQ_SEQ;
DROP SEQUENCE BOARD_ANNOUNCE_SEQ;
DROP SEQUENCE ZZIM_SEQ;
DROP SEQUENCE PRODUCT_CATEGORY_SEQ;
DROP SEQUENCE MEMBER_SEQ;

<<<<<<< HEAD

-- 새로운 시퀀스 생성
CREATE SEQUENCE WM_MEMBER_HOME_SEQ NOCACHE;
CREATE SEQUENCE WM_MEMBER_SEQ NOCACHE;
CREATE SEQUENCE WM_COUPON_SEQ NOCACHE;
CREATE SEQUENCE WM_PRODUCT_SEQ NOCACHE;
CREATE SEQUENCE WM_ZZIM_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ANNOUNCE_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_FAQ_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ASK_SEQ NOCACHE;
CREATE SEQUENCE WM_BOARD_ANSWER_SEQ NOCACHE;
CREATE SEQUENCE WM_CART_SEQ NOCACHE;
CREATE SEQUENCE WM_ORDER_SEQ NOCACHE;
CREATE SEQUENCE WM_ORDER_DETAIL_SEQ NOCACHE;

-- 기존 테이블 삭제
DROP TABLE WM_ORDER_DETAIL;
DROP TABLE WM_ORDER;
DROP TABLE WM_CART;
DROP TABLE WM_BOARD_ANSWER;
DROP TABLE WM_BOARD_ASK;
DROP TABLE WM_BOARD_FAQ;
DROP TABLE WM_BOARD_ANNOUNCE;
DROP TABLE WM_ZZIM;
DROP TABLE WM_COUPON;
DROP TABLE WM_PRODUCT_MANAGE;
DROP TABLE WM_PRODUCT;
DROP TABLE WM_MEMBER_EXP;
DROP TABLE WM_MEMBER_HOME;
DROP TABLE WM_MEMBER;
=======
CREATE SEQUENCE MEMBER_SEQ NOCACHE;
CREATE SEQUENCE PRODUCT_CATEGORY_SEQ NOCACHE;
CREATE SEQUENCE ZZIM_SEQ NOCACHE;
CREATE SEQUENCE BOARD_ANNOUNCE_SEQ NOCACHE;
CREATE SEQUENCE BOARD_FAQ_SEQ NOCACHE;
CREATE SEQUENCE BOARD_ASK_SEQ NOCACHE;
CREATE SEQUENCE BOARD_ANSWER_SEQ NOCACHE;
CREATE SEQUENCE CART_SEQ NOCACHE;
CREATE SEQUENCE ORDER_SEQ NOCACHE;
CREATE SEQUENCE ORDER_DETAIL_SEQ NOCACHE;
CREATE SEQUENCE CP_SEQ NOCACHE;
>>>>>>> main



DROP TABLE CP_ISSUE;
DROP TABLE CP;
DROP TABLE ORDER_DETAIL;
DROP TABLE ORDER_T;
DROP TABLE CART;
DROP TABLE BOARD_ANSWER;
DROP TABLE BOARD_ASK;
DROP TABLE BOARD_FAQ;
DROP TABLE BOARD_ANNOUNCE;
DROP TABLE ZZIM;
DROP TABLE PRODUCT_IMAGE;
DROP TABLE PRODUCT_CATEGORY;
DROP TABLE PRODUCT;
DROP TABLE MEMBER_EXP;
DROP TABLE MEMBER_INACTIVE;
DROP TABLE MEMBER;


CREATE TABLE MEMBER (
    NUM              NUMBER                 NOT NULL,      
    NAME             VARCHAR2(30 BYTE)      NOT NULL,        
    PW               VARCHAR2(20 BYTE),       
    CELL             VARCHAR2(20 BYTE)      NOT NULL UNIQUE, 
    EMAIL            VARCHAR2(20 BYTE)      NOT NULL UNIQUE, 
    POSTCODE         VARCHAR2(20 BYTE)      NULL,        
    JIBUNADDRESS     VARCHAR2(90 BYTE)      NULL,   
    ROADADDRESS      VARCHAR2(90 BYTE)      NULL,  
    DETAILADDRESS    VARCHAR2(90 BYTE)      NULL,
    BIRTH            VARCHAR2(10 BYTE)      NULL,
    GENDER           NUMBER(1)              NULL,
    MDATE            DATE,                              
    AUTH             NUMBER(5)              NULL, 
    REG_DATE         DATE                   NOT NULL,
    CONSTRAINT PK_WM_MEMBER PRIMARY KEY(NUM)
);

CREATE TABLE MEMBER_INACTIVE (
    NUM              NUMBER                 NOT NULL,      
    NAME             VARCHAR2(30 BYTE)      NOT NULL,        
    PW               VARCHAR2(20 BYTE),       
    CELL             VARCHAR2(20 BYTE)      NOT NULL UNIQUE, 
    EMAIL            VARCHAR2(20 BYTE)      NOT NULL UNIQUE, 
    POSTCODE         VARCHAR2(20 BYTE)      NULL,        
    JIBUNADDRESS     VARCHAR2(90 BYTE)      NULL,   
    ROADADDRESS      VARCHAR2(90 BYTE)      NULL,  
    DETAILADDRESS    VARCHAR2(90 BYTE)      NULL,
    BIRTH            VARCHAR2(10 BYTE)      NULL,
    GENDER           NUMBER(1)              NULL,
    MDATE            DATE                   NULL,                              
    AUTH             NUMBER(5)              NULL, 
    REG_DATE         DATE                   NOT NULL,
    STOP_DATE        DATE                   NOT NULL,
    CONSTRAINT PK_WM_MEMBER_INACTIVE PRIMARY KEY(NUM)
);


CREATE TABLE MEMBER_EXP (
    EMAIL          VARCHAR2(50 BYTE) NOT NULL UNIQUE,  -- 탈퇴한 회원 이메일
    REG_DATE       DATE,                               -- 가입일
    EXP_DATE       DATE                                -- 탈퇴일
);
-- 제품 상세
CREATE TABLE PRODUCT(
	PRDT_NUM        NUMBER(5)        NOT NULL,        -- 제품 식별 번호
	PRDT_NAME       VARCHAR2(60)     NOT NULL,	     -- 제품 이름
	PRDT_TITLE      VARCHAR2(100)    NOT NULL,	     -- 제품 타이틀
	PRDT_INFO       VARCHAR2(1000)   NOT NULL,        -- 제품 정보
	PRDT_ORIGIN     VARCHAR2(60)     NOT NULL,	     -- 제품 원산지
	PRDT_REAL_PRICE NUMBER(7)        NOT NULL,        -- 제품 원가
	PRDT_PRICE      NUMBER(7)        NOT NULL,	     -- 제품 정가
	PRDT_STOCK      NUMBER(7)        NOT NULL,
    PRDT_CATAGORY   NUMBER(5)        NOT NULL,
    PRDT_HIT        NUMBER(8)        NOT NULL,
 CONSTRAINT PK_PRODUCT PRIMARY KEY (PRDT_NUM)

);

-- 제품 카테고리
CREATE TABLE PRODUCT_CATEGORY(
  PRDT_NUM       NUMBER(5) NOT NULL,
  PRDT_CATEGORY  NUMBER(5) NOT NULL,
  
  CONSTRAINT PW_PRODUCT_CATEGORY PRIMARY KEY (PRDT_NUM),
  CONSTRAINT FK_PRODUCT_CATEGORY FOREIGN KEY (PRDT_NUM) REFERENCES PRODUCT(PRDT_NUM)

);

-- 제품 이미지
CREATE TABLE PRODUCT_IMAGE(
    PRDT_NUM        NUMBER(5)            NOT NULL,        -- 제품 식별 번호
    IMAGE_PATH      VARCHAR2(100 BYTE)   NOT NULL,
    FILESYSTEM_NAME VARCHAR2(100 BYTE)   NOT NULL,
    
    CONSTRAINT FK_PRODUCT_IMAGE FOREIGN KEY(PRDT_NUM) REFERENCES PRODUCT(PRDT_NUM) ON DELETE CASCADE
    
);


-- 찜 목록을 저장하기 위한 테이블
CREATE TABLE ZZIM (
	ZZIM_NUM    NUMBER(5) NOT NULL,          -- 찜 번호
	NUM         NUMBER   NOT NULL,          -- 회원 번호
	PRDT_NUM NUMBER(5) NOT NULL,          -- 제품 번호
	CONSTRAINT PK_ZZIM PRIMARY KEY(ZZIM_NUM),
	CONSTRAINT FK_MEMBER_ZZIM FOREIGN KEY(NUM) REFERENCES MEMBER(NUM) ON DELETE CASCADE,
	CONSTRAINT FK2_PRODUCT_ZZIM FOREIGN KEY(PRDT_NUM) REFERENCES PRODUCT(PRDT_NUM) ON DELETE CASCADE
);

-- 공지사항 정보를 저장하기 위한 테이블
CREATE TABLE BOARD_ANNOUNCE (
	ANN_NUM NUMBER NOT NULL,                            -- 공지사항 번호
	ANN_TITLE VARCHAR2(300) NOT NULL,          -- 공지사항 제목
	ANN_CONTENT VARCHAR2(1000) NOT NULL,       -- 공지사항 내용
    ANN_FILE VARCHAR2(100) NULL,  --공지사항첨부파일
	ANN_DATE DATE DEFAULT SYSDATE NOT NULL,    -- 등록일
	CONSTRAINT PK_BOARD_ANNOUNCE PRIMARY KEY (ANN_NUM)
);


-- FAQ 정보를 저장하기 위한 테이블
CREATE TABLE BOARD_FAQ (
	FAQ_NUM NUMBER,                         -- FAQ 번호
	FAQ_TITLE VARCHAR2(300) NOT NULL,       -- FAQ 제목
	FAQ_CONTENT VARCHAR2(3000) NOT NULL,    -- FAQ 내용
	FAQ_CATEGORY NUMBER(1) DEFAULT 1 NOT NULL, -- FAQ 카테고리
	FAQ_DATE DATE DEFAULT SYSDATE NOT NULL, -- FAQ 작성일
	CONSTRAINT PK_BOARD_FAQ PRIMARY KEY (FAQ_NUM)
);



-- 1:1 문의 게시판 정보를 저장하기 위한 테이블
CREATE TABLE BOARD_ASK (
	ASK_NUM NUMBER,                          -- 문의글 번호
	NUM     NUMBER NOT NULL,                 -- 문의자 번호
	ASK_TITLE VARCHAR2(100) NOT NULL,        -- 문의글 제목
	ASK_CONTENT VARCHAR2(1000) NOT NULL,     -- 문의글 내용
	ASK_FILE VARCHAR2(100) NULL,              -- 문의글 파일 첨부
	ASK_DATE DATE DEFAULT SYSDATE NOT NULL,  -- 문의글 작성 날짜
    AKS_STATE NUMBER(1) DEFAULT 0 NOT NULL,   -- 문의글 상태
	CONSTRAINT PK_BOARD_ASK PRIMARY KEY (ASK_NUM),
	CONSTRAINT FK_BOARD_ASK FOREIGN KEY (NUM) REFERENCES MEMBER(NUM) ON DELETE CASCADE
);


-- 1:1 문의 게시판 답변 정보를 저장하기 위한 테이블
CREATE TABLE BOARD_ANSWER (
	ASK_NUM NUMBER NOT NULL,                   -- 문의글 번호
    NUM     NUMBER NOT NULL,                   -- 문의자 번호
	ANSWER_NUM NUMBER(5),                      -- 답변 번호
	ANSWER_CONTENT VARCHAR2(1000) NOT NULL,    -- 답변 내용
	ANSWER_PHOTO VARCHAR2(100),                -- 답변 사진 첨부
	ANSWER_DATE DATE DEFAULT SYSDATE NOT NULL, -- 답변 작성 날짜
	CONSTRAINT PK_BOARD_ANSWER PRIMARY KEY (ANSWER_NUM),
	CONSTRAINT FK1_BOARD_ANSWER FOREIGN KEY (NUM) REFERENCES MEMBER (NUM) ON DELETE CASCADE,
    CONSTRAINT FK2_BOARD_ANSWER FOREIGN KEY (ASK_NUM) REFERENCES BOARD_ASK (ASK_NUM) ON DELETE CASCADE
);

-- 장바구니 정보를 저장하기 위한 테이블
CREATE TABLE CART (
	CART_NUM     NUMBER(20)   NOT NULL, -- 장바구니 번호
	PRDT_NUM     NUMBER       NOT NULL, -- 제품 번호
	NUM          NUMBER       NOT NULL, -- 회원 번호
	PRDT_QTY     NUMBER       NOT NULL, -- 제품 수량
	CONSTRAINT   PK_CART      PRIMARY KEY (CART_NUM),
	CONSTRAINT   FK_CART      FOREIGN KEY (PRDT_NUM) REFERENCES PRODUCT (PRDT_NUM) ON DELETE CASCADE,
	CONSTRAINT   FK2_CART     FOREIGN KEY (NUM)      REFERENCES MEMBER  (NUM)      ON DELETE CASCADE
);

-- 주문 정보를 저장하기 위한 테이블
CREATE TABLE ORDER_T (
	ORDER_NUM             NUMBER          NOT NULL,  -- 주문번호
	NUM                   NUMBER          NOT NULL,  -- 회원번호
	ORDER_TOTAL_PRICE     NUMBER(10)      NOT NULL,  -- 구매금액 : 각 주문번호 ORDER_PRICE의 합-쿠폰
	ORDER_STATUS          NUMBER(1)       NOT NULL,  -- 상품 주문 상태 (0: 주문 완료, 1: 배송중, 2: 배송완료)
	ORDER_DATE            DATE            NOT NULL,  -- 구매일
	ORDER_NOTICE          VARCHAR2(100),             -- 배송요청사항
	RECEIVER_NAME         VARCHAR2(20)    NOT NULL,  -- 수령자 이름
	RECEIVER_PHONE        VARCHAR2(20)    NOT NULL,  -- 수령자 휴대폰번호
	ORDERER_NAME          VARCHAR2(20)    NOT NULL,  -- 주문자 이름
	ORDERER_PHONE         VARCHAR2(20)    NOT NULL,  -- 주문자 휴대폰번호
	DELIVERY_METHOD       VARCHAR2(40)    NOT NULL,  -- 배송방법
	PAY_METHOD            VARCHAR2(200)   NOT NULL,  -- 결제방법
	CARD_NAME             VARCHAR2(50),              -- 카드 이름
	CARD_PAY              VARCHAR2(20),              -- 할부개월
	CONSTRAINT            PK_ORDER        PRIMARY KEY (ORDER_NUM),
	CONSTRAINT            FK_ORDER        FOREIGN KEY (NUM) REFERENCES MEMBER(NUM) ON DELETE SET NULL
);

-- 주문 상세 정보를 저장하기 위한 테이블
CREATE TABLE ORDER_DETAIL (
	ORDER_DETAIL_NUM     NUMBER       NOT NULL,   -- 구매상세 식별번호
	ORDER_NUM            NUMBER       NOT NULL,   -- 주문번호
	PRDT_NUM             NUMBER(5)    NOT NULL,   -- 제품번호
	ORDER_TOTAL          NUMBER(7)    NOT NULL,   -- 제품구매총액 (상품개수*상품가격)
    ORDER_QTY            NUMBER(5)    NOT NULL,   -- 제품구매개수
	CONSTRAINT           PK_ORDER_DETAIL        PRIMARY KEY (ORDER_DETAIL_NUM),
	CONSTRAINT           FK_ORDER_DETAIL        FOREIGN KEY (ORDER_NUM)         REFERENCES ORDER_T (ORDER_NUM)     ON DELETE CASCADE,
	CONSTRAINT           FK2_ORDER_DETAIL       FOREIGN KEY (PRDT_NUM)          REFERENCES PRODUCT (PRDT_NUM) ON DELETE SET NULL
);  

--쿠폰 정보
CREATE TABLE CP (
  CP_NUM          NUMBER           NOT NULL,     -- 쿠폰 번호
  CP_NAME         VARCHAR2(50)     NOT NULL,     -- 쿠폰 이름
  CP_INFO         VARCHAR2(100)    NOT NULL,     -- 쿠폰 정보
  CP_PRICE        NUMBER(7)        NOT NULL,     -- 쿠폰 가격
  CREATE_AT       DATE             NOT NULL,     -- 쿠폰 시작일
  END_AT          DATE             NOT NULL,     -- 쿠폰 만료일

 CONSTRAINT PK_CP PRIMARY KEY (CP_NUM)
);

-- 쿠폰 발급 내역
CREATE TABLE CP_ISSUE (
  NUM     NUMBER NOT NULL,
  CP_NUM  NUMBER NOT NULL,
  CP_USE  NUMBER NOT NULL,    -- (1:미사용, 2: 사용)
  
CONSTRAINT FK_CP_ISSUE FOREIGN KEY (NUM) REFERENCES MEMBER(NUM) ON DELETE CASCADE,
CONSTRAINT FK2_CP_ISSUE FOREIGN KEY (CP_NUM) REFERENCES CP(CP_NUM) ON DELETE CASCADE
   
);
